[build]
  command = "npm run build:website"
  publish = "website/dist"
  ignore = "false"

[context.production]
  command = "npm run build:website"
  publish = "website/dist"

[context.deploy-preview]
  command = "npm run build:website"
  publish = "website/dist"

[context.branch-deploy]
  command = "npm run build:website"
  publish = "website/dist"