[build]
  command = "vp run website:build"
  publish = "website/dist"
  ignore = "false"

[context.production]
  command = "vp run website:build"
  publish = "website/dist"

[context.deploy-preview]
  command = "vp run website:build"
  publish = "website/dist"

[context.branch-deploy]
  command = "vp run website:build"
  publish = "website/dist"